AdvancedOptions: false
DockerFilePath: Dockerfile
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: ap-southeast-1
RepoName: LYH-RAIN/vue-color-avatar
RegionId: ap-southeast-1
CustomParameters: ''
Owner: LYH-RAIN
Branch: dddddd
Platform: github
