{"DockerFilePath":"Dockerfile","ServiceType":"private","AllowedRegions":["ap-southeast-1"],"ArtifactSourceType":"Dockerfile","RepoName":"LYH-RAIN/vue-color-avatar","Arch":"EcsSingle","RegionId":"ap-southeast-1","DockerBuildArgs":{}}
