Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      RoleName: ComputeNestDeploy
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: Template
          Url: 'ros_templates/template.yaml'
          PredefinedParameters: []
          HiddenParameterKeys:
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: vpc-bp17crlxe948tz7vwe9a5
                    ZoneId: cn-hangzhou-i
                    VSwitchId: vsw-bp1jb3ni4vtq5gd6apbv2
      AcrImageArtifactRelation:
        # 相应的，ros模板中也需要采用该伪参数
        '{{ computenest::acrimage::LYH-RAIN_vue-color-avatar-dockerfile }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: demo
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: AcrImage
    # 采用与image_name相同的ArtifactName
    ArtifactName: lyh-rain_vue-color-avatar-dockerfile
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_1.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_1.Tag}
      RepoType: Private
AcrImageBuilder:
  AcrImage_1:
    # dockerfile路径
    DockerFilePath: Dockerfile
    # 采用与image_name相同的repoName
    RepoName: lyh-rain_vue-color-avatar-dockerfile
    Tag: latest
    DockerBuildArgs: {}